name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  CI:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./gradlew spotlessCheck
      - run: ./gradlew test
